package redisqueue

// Message represents a Redis stream message with its metadata and payload.
//
// Messages are the fundamental unit of data passed through Redis streams.
// Each message contains an ID (assigned by Redis), the target stream name,
// and a key-value payload.
type Message struct {
	// ID is the unique message identifier within the stream.
	// Format: "timestamp-sequence" (e.g., "1640995200000-0")
	// Auto-generated by Redis when empty during enqueue.
	ID string

	// Stream is the name of the Redis stream this message belongs to.
	Stream string

	// Values contains the message payload as key-value pairs.
	// All values must be serializable (strings, numbers, booleans, etc).
	Values map[string]interface{}
}
