package redisqueue

// Message
// ID is generated by Redis. Input is empty.
// Stream is the redis creation of stream name.
// Values is message carrying parameter list.
type Message struct {
	ID     string
	Stream string
	Values map[string]interface{}
}
